// GENERATED by tools/dev-icons/generate.ts — do not edit; edit tools/dev-icons/manifest.json and re-run `bun tools/dev-icons/generate.ts`
// Source: @tabler/icons@3.48.0 icons/outline (MIT) — vendored in tools/dev-icons/vendor/tabler/;
// attribution in tools/dev-icons/THIRD-PARTY-NOTICES.md.

// Structural twin of IconGlyphElement in ./icon-glyphs.ts (kept local to
// avoid an import cycle — the shapes must stay assignment-compatible).
type IconGlyphElement =
  | { kind: "path"; d: string }
  | { kind: "circle"; cx: number; cy: number; r: number }
  | { kind: "line"; x1: number; y1: number; x2: number; y2: number };

/** Tabler outline geometry per glyph id — 24-unit grid, stroke paint, bounding-box path stripped. */
export const TABLER_ICON_GLYPH_ELEMENTS: Record<
  string,
  { viewBoxSize: number; elements: readonly IconGlyphElement[] }
> = {
  // tabler: activity
  "activity": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 12h4l3 8l4 -16l3 8h4" },
    ],
  },
  // tabler: robot
  "agent": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6 6a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -4" },
      { kind: "path", d: "M12 2v2" },
      { kind: "path", d: "M9 12v9" },
      { kind: "path", d: "M15 12v9" },
      { kind: "path", d: "M5 16l4 -2" },
      { kind: "path", d: "M15 14l4 2" },
      { kind: "path", d: "M9 18h6" },
      { kind: "path", d: "M10 8v.01" },
      { kind: "path", d: "M14 8v.01" },
    ],
  },
  // tabler: api
  "api": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4 13h5" },
      { kind: "path", d: "M12 16v-8h3a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-3" },
      { kind: "path", d: "M20 8v8" },
      { kind: "path", d: "M9 16v-5.5a2.5 2.5 0 0 0 -5 0v5.5" },
    ],
  },
  // tabler: archive
  "archive": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 6a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2" },
      { kind: "path", d: "M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-10" },
      { kind: "path", d: "M10 12l4 0" },
    ],
  },
  // tabler: bell
  "bell": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" },
      { kind: "path", d: "M9 17v1a3 3 0 0 0 6 0v-1" },
    ],
  },
  // tabler: brain
  "brain": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M15.5 13a3.5 3.5 0 0 0 -3.5 3.5v1a3.5 3.5 0 0 0 7 0v-1.8" },
      { kind: "path", d: "M8.5 13a3.5 3.5 0 0 1 3.5 3.5v1a3.5 3.5 0 0 1 -7 0v-1.8" },
      { kind: "path", d: "M17.5 16a3.5 3.5 0 0 0 0 -7h-.5" },
      { kind: "path", d: "M19 9.3v-2.8a3.5 3.5 0 0 0 -7 0" },
      { kind: "path", d: "M6.5 16a3.5 3.5 0 0 1 0 -7h.5" },
      { kind: "path", d: "M5 9.3v-2.8a3.5 3.5 0 0 1 7 0v10" },
    ],
  },
  // tabler: git-branch
  "branch": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M15 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M7 8l0 8" },
      { kind: "path", d: "M9 18h6a2 2 0 0 0 2 -2v-5" },
      { kind: "path", d: "M14 14l3 -3l3 3" },
    ],
  },
  // tabler: app-window
  "browser": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10" },
      { kind: "path", d: "M6 8h.01" },
      { kind: "path", d: "M9 8h.01" },
    ],
  },
  // tabler: bug
  "bug": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M9 9v-1a3 3 0 0 1 6 0v1" },
      { kind: "path", d: "M8 9h8a6 6 0 0 1 1 3v3a5 5 0 0 1 -10 0v-3a6 6 0 0 1 1 -3" },
      { kind: "path", d: "M3 13l4 0" },
      { kind: "path", d: "M17 13l4 0" },
      { kind: "path", d: "M12 20l0 -6" },
      { kind: "path", d: "M4 19l3.35 -2" },
      { kind: "path", d: "M20 19l-3.35 -2" },
      { kind: "path", d: "M4 7l3.75 2.4" },
      { kind: "path", d: "M20 7l-3.75 2.4" },
    ],
  },
  // tabler: server-bolt
  "cache": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-2" },
      { kind: "path", d: "M15 20h-9a3 3 0 0 1 -3 -3v-2a3 3 0 0 1 3 -3h12" },
      { kind: "path", d: "M7 8v.01" },
      { kind: "path", d: "M7 16v.01" },
      { kind: "path", d: "M20 15l-2 3h3l-2 3" },
    ],
  },
  // tabler: chart-bar
  "chart": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -6" },
      { kind: "path", d: "M15 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -10" },
      { kind: "path", d: "M9 5a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -14" },
      { kind: "path", d: "M4 20h14" },
    ],
  },
  // tabler: cloud
  "cloud": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6.657 18c-2.572 0 -4.657 -2.007 -4.657 -4.483c0 -2.475 2.085 -4.482 4.657 -4.482c.393 -1.762 1.794 -3.2 3.675 -3.773c1.88 -.572 3.956 -.193 5.444 1c1.488 1.19 2.162 3.007 1.77 4.769h.99c1.913 0 3.464 1.56 3.464 3.486c0 1.927 -1.551 3.487 -3.465 3.487h-11.878" },
    ],
  },
  // tabler: code
  "code": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M7 8l-4 4l4 4" },
      { kind: "path", d: "M17 8l4 4l-4 4" },
      { kind: "path", d: "M14 4l-4 16" },
    ],
  },
  // tabler: file-code
  "code-file": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M14 3v4a1 1 0 0 0 1 1h4" },
      { kind: "path", d: "M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2" },
      { kind: "path", d: "M10 13l-1 2l1 2" },
      { kind: "path", d: "M14 13l1 2l-1 2" },
    ],
  },
  // tabler: coin
  "coin": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" },
      { kind: "path", d: "M14.8 9a2 2 0 0 0 -1.8 -1h-2a2 2 0 1 0 0 4h2a2 2 0 1 1 0 4h-2a2 2 0 0 1 -1.8 -1" },
      { kind: "path", d: "M12 7v10" },
    ],
  },
  // tabler: git-commit
  "commit": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" },
      { kind: "path", d: "M12 3l0 6" },
      { kind: "path", d: "M12 15l0 6" },
    ],
  },
  // tabler: settings
  "config": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065" },
      { kind: "path", d: "M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" },
    ],
  },
  // tabler: container
  "container": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M20 4v.01" },
      { kind: "path", d: "M20 20v.01" },
      { kind: "path", d: "M20 16v.01" },
      { kind: "path", d: "M20 12v.01" },
      { kind: "path", d: "M20 8v.01" },
      { kind: "path", d: "M8 5a1 1 0 0 1 1 -1h6a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-6a1 1 0 0 1 -1 -1l0 -14" },
      { kind: "path", d: "M4 4v.01" },
      { kind: "path", d: "M4 20v.01" },
      { kind: "path", d: "M4 16v.01" },
      { kind: "path", d: "M4 12v.01" },
      { kind: "path", d: "M4 8v.01" },
    ],
  },
  // tabler: cpu
  "cpu": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 6a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -12" },
      { kind: "path", d: "M9 9h6v6h-6l0 -6" },
      { kind: "path", d: "M3 10h2" },
      { kind: "path", d: "M3 14h2" },
      { kind: "path", d: "M10 3v2" },
      { kind: "path", d: "M14 3v2" },
      { kind: "path", d: "M21 10h-2" },
      { kind: "path", d: "M21 14h-2" },
      { kind: "path", d: "M14 21v-2" },
      { kind: "path", d: "M10 21v-2" },
    ],
  },
  // tabler: layout-dashboard
  "dashboard": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 4h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1" },
      { kind: "path", d: "M5 16h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1" },
      { kind: "path", d: "M15 12h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1" },
      { kind: "path", d: "M15 4h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1" },
    ],
  },
  // tabler: database
  "database": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4 6a8 3 0 1 0 16 0a8 3 0 1 0 -16 0" },
      { kind: "path", d: "M4 6v6a8 3 0 0 0 16 0v-6" },
      { kind: "path", d: "M4 12v6a8 3 0 0 0 16 0v-6" },
    ],
  },
  // tabler: device-desktop
  "desktop": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 5a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1v-10" },
      { kind: "path", d: "M7 20h10" },
      { kind: "path", d: "M9 16v4" },
      { kind: "path", d: "M15 16v4" },
    ],
  },
  // tabler: file-text
  "document": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M14 3v4a1 1 0 0 0 1 1h4" },
      { kind: "path", d: "M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2" },
      { kind: "path", d: "M9 9l1 0" },
      { kind: "path", d: "M9 13l6 0" },
      { kind: "path", d: "M9 17l6 0" },
    ],
  },
  // tabler: files
  "documents": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M15 3v4a1 1 0 0 0 1 1h4" },
      { kind: "path", d: "M18 17h-7a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2h4l5 5v7a2 2 0 0 1 -2 2" },
      { kind: "path", d: "M16 17v2a2 2 0 0 1 -2 2h-7a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2h2" },
    ],
  },
  // tabler: checklist
  "eval": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" },
      { kind: "path", d: "M14 19l2 2l4 -4" },
      { kind: "path", d: "M9 8h4" },
      { kind: "path", d: "M9 12h2" },
    ],
  },
  // tabler: bolt
  "event": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M13 3l0 7l6 0l-8 11l0 -7l-6 0l8 -11" },
    ],
  },
  // tabler: filter
  "filter": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4 4h16v2.172a2 2 0 0 1 -.586 1.414l-4.414 4.414v7l-6 2v-8.5l-4.48 -4.928a2 2 0 0 1 -.52 -1.345v-2.227" },
    ],
  },
  // tabler: folder
  "folder": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 4h4l3 3h7a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2" },
    ],
  },
  // tabler: lambda
  "function": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6 20l6.5 -9" },
      { kind: "path", d: "M19 20c-6 0 -6 -16 -12 -16" },
    ],
  },
  // tabler: gauge
  "gauge": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" },
      { kind: "path", d: "M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" },
      { kind: "path", d: "M13.41 10.59l2.59 -2.59" },
      { kind: "path", d: "M7 12a5 5 0 0 1 5 -5" },
    ],
  },
  // tabler: world
  "globe": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" },
      { kind: "path", d: "M3.6 9h16.8" },
      { kind: "path", d: "M3.6 15h16.8" },
      { kind: "path", d: "M11.5 3a17 17 0 0 0 0 18" },
      { kind: "path", d: "M12.5 3a17 17 0 0 1 0 18" },
    ],
  },
  // tabler: shield-check
  "guardrail": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M11.46 20.846a12 12 0 0 1 -7.96 -14.846a12 12 0 0 0 8.5 -3a12 12 0 0 0 8.5 3a12 12 0 0 1 -.09 7.06" },
      { kind: "path", d: "M15 19l2 2l4 -4" },
    ],
  },
  // tabler: user
  "human": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" },
      { kind: "path", d: "M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" },
    ],
  },
  // tabler: gavel
  "judge": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M13 10l7.383 7.418c.823 .82 .823 2.148 0 2.967a2.11 2.11 0 0 1 -2.976 0l-7.407 -7.385" },
      { kind: "path", d: "M6 9l4 4" },
      { kind: "path", d: "M13 10l-4 -4" },
      { kind: "path", d: "M3 21h7" },
      { kind: "path", d: "M6.793 15.793l-3.586 -3.586a1 1 0 0 1 0 -1.414l2.293 -2.293l.5 .5l3 -3l-.5 -.5l2.293 -2.293a1 1 0 0 1 1.414 0l3.586 3.586a1 1 0 0 1 0 1.414l-2.293 2.293l-.5 -.5l-3 3l.5 .5l-2.293 2.293a1 1 0 0 1 -1.414 0" },
    ],
  },
  // tabler: key
  "key": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M16.555 3.843l3.602 3.602a2.877 2.877 0 0 1 0 4.069l-2.643 2.643a2.877 2.877 0 0 1 -4.069 0l-.301 -.301l-6.558 6.558a2 2 0 0 1 -1.239 .578l-.175 .008h-1.172a1 1 0 0 1 -.993 -.883l-.007 -.117v-1.172a2 2 0 0 1 .467 -1.284l.119 -.13l.414 -.414h2v-2h2v-2l2.144 -2.144l-.301 -.301a2.877 2.877 0 0 1 0 -4.069l2.643 -2.643a2.877 2.877 0 0 1 4.069 0" },
      { kind: "path", d: "M15 9h.01" },
    ],
  },
  // tabler: book
  "knowledge": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0" },
      { kind: "path", d: "M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0" },
      { kind: "path", d: "M3 6l0 13" },
      { kind: "path", d: "M12 6l0 13" },
      { kind: "path", d: "M21 6l0 13" },
    ],
  },
  // tabler: device-laptop
  "laptop": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 19l18 0" },
      { kind: "path", d: "M5 7a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v8a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -8" },
    ],
  },
  // tabler: stack-2
  "layers": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M12 4l-8 4l8 4l8 -4l-8 -4" },
      { kind: "path", d: "M4 12l8 4l8 -4" },
      { kind: "path", d: "M4 16l8 4l8 -4" },
    ],
  },
  // tabler: link
  "link": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M9 15l6 -6" },
      { kind: "path", d: "M11 6l.463 -.536a5 5 0 0 1 7.071 7.072l-.534 .464" },
      { kind: "path", d: "M13 18l-.397 .534a5.068 5.068 0 0 1 -7.127 0a4.972 4.972 0 0 1 0 -7.071l.524 -.463" },
    ],
  },
  // tabler: lock
  "lock": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 13a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6" },
      { kind: "path", d: "M11 16a1 1 0 1 0 2 0a1 1 0 0 0 -2 0" },
      { kind: "path", d: "M8 11v-4a4 4 0 1 1 8 0v4" },
    ],
  },
  // tabler: repeat
  "loop": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4 12v-3a3 3 0 0 1 3 -3h13m-3 -3l3 3l-3 3" },
      { kind: "path", d: "M20 12v3a3 3 0 0 1 -3 3h-13m3 3l-3 -3l3 -3" },
    ],
  },
  // tabler: mail
  "mail": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10" },
      { kind: "path", d: "M3 7l9 6l9 -6" },
    ],
  },
  // tabler: database
  "memory": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4 6a8 3 0 1 0 16 0a8 3 0 1 0 -16 0" },
      { kind: "path", d: "M4 6v6a8 3 0 0 0 16 0v-6" },
      { kind: "path", d: "M4 12v6a8 3 0 0 0 16 0v-6" },
    ],
  },
  // tabler: git-merge
  "merge": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M15 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M7 8l0 8" },
      { kind: "path", d: "M7 8a4 4 0 0 0 4 4h4" },
    ],
  },
  // tabler: message
  "message": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M8 9h8" },
      { kind: "path", d: "M8 13h6" },
      { kind: "path", d: "M18 4a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-5l-5 3v-3h-2a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3h12" },
    ],
  },
  // tabler: device-mobile
  "mobile": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6 5a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-14" },
      { kind: "path", d: "M11 4h2" },
      { kind: "path", d: "M12 17v.01" },
    ],
  },
  // tabler: sparkles
  "model": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6" },
    ],
  },
  // tabler: device-desktop-analytics
  "monitor": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 5a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1l0 -10" },
      { kind: "path", d: "M7 20h10" },
      { kind: "path", d: "M9 16v4" },
      { kind: "path", d: "M15 16v4" },
      { kind: "path", d: "M9 12v-4" },
      { kind: "path", d: "M12 12v-1" },
      { kind: "path", d: "M15 12v-2" },
      { kind: "path", d: "M12 12v-1" },
    ],
  },
  // tabler: network
  "network": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6 9a6 6 0 1 0 12 0a6 6 0 0 0 -12 0" },
      { kind: "path", d: "M12 3c1.333 .333 2 2.333 2 6s-.667 5.667 -2 6" },
      { kind: "path", d: "M12 3c-1.333 .333 -2 2.333 -2 6s.667 5.667 2 6" },
      { kind: "path", d: "M6 9h12" },
      { kind: "path", d: "M3 20h7" },
      { kind: "path", d: "M14 20h7" },
      { kind: "path", d: "M10 20a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" },
      { kind: "path", d: "M12 15v3" },
    ],
  },
  // tabler: sitemap
  "orchestrator": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 17a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2l0 -2" },
      { kind: "path", d: "M15 17a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2l0 -2" },
      { kind: "path", d: "M9 5a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2l0 -2" },
      { kind: "path", d: "M6 15v-1a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v1" },
      { kind: "path", d: "M12 9l0 3" },
    ],
  },
  // tabler: package
  "package": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5" },
      { kind: "path", d: "M12 12l8 -4.5" },
      { kind: "path", d: "M12 12l0 9" },
      { kind: "path", d: "M12 12l-8 -4.5" },
      { kind: "path", d: "M16 5.25l-8 4.5" },
    ],
  },
  // tabler: plug-connected
  "plug": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M7 12l5 5l-1.5 1.5a3.536 3.536 0 1 1 -5 -5l1.5 -1.5" },
      { kind: "path", d: "M17 12l-5 -5l1.5 -1.5a3.536 3.536 0 1 1 5 5l-1.5 1.5" },
      { kind: "path", d: "M3 21l2.5 -2.5" },
      { kind: "path", d: "M18.5 5.5l2.5 -2.5" },
      { kind: "path", d: "M10 11l-2 2" },
      { kind: "path", d: "M13 14l-2 2" },
    ],
  },
  // tabler: git-pull-request
  "pull-request": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M4 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M16 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" },
      { kind: "path", d: "M6 8l0 8" },
      { kind: "path", d: "M11 6h5a2 2 0 0 1 2 2v8" },
      { kind: "path", d: "M14 9l-3 -3l3 -3" },
    ],
  },
  // tabler: stack-push
  "queue": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6 10l-2 1l8 4l8 -4l-2 -1" },
      { kind: "path", d: "M4 15l8 4l8 -4" },
      { kind: "path", d: "M12 4v7" },
      { kind: "path", d: "M15 8l-3 3l-3 -3" },
    ],
  },
  // tabler: route
  "route": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" },
      { kind: "path", d: "M19 7a2 2 0 1 0 0 -4a2 2 0 0 0 0 4" },
      { kind: "path", d: "M11 19h5.5a3.5 3.5 0 0 0 0 -7h-8a3.5 3.5 0 0 1 0 -7h4.5" },
    ],
  },
  // tabler: clock
  "schedule": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" },
      { kind: "path", d: "M12 7v5l3 3" },
    ],
  },
  // tabler: search
  "search": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" },
      { kind: "path", d: "M21 21l-6 -6" },
    ],
  },
  // tabler: send
  "send": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M10 14l11 -11" },
      { kind: "path", d: "M21 3l-6.5 18a.55 .55 0 0 1 -1 0l-3.5 -7l-7 -3.5a.55 .55 0 0 1 0 -1l18 -6.5" },
    ],
  },
  // tabler: server
  "server": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-2" },
      { kind: "path", d: "M3 15a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3l0 -2" },
      { kind: "path", d: "M7 8l0 .01" },
      { kind: "path", d: "M7 16l0 .01" },
    ],
  },
  // tabler: table
  "table": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14" },
      { kind: "path", d: "M3 10h18" },
      { kind: "path", d: "M10 3v18" },
    ],
  },
  // tabler: terminal-2
  "terminal": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M8 9l3 3l-3 3" },
      { kind: "path", d: "M13 15l3 0" },
      { kind: "path", d: "M3 6a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2l0 -12" },
    ],
  },
  // tabler: tool
  "tool": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M7 10h3v-3l-3.5 -3.5a6 6 0 0 1 8 8l6 6a2 2 0 0 1 -3 3l-6 -6a6 6 0 0 1 -8 -8l3.5 3.5" },
    ],
  },
  // tabler: users
  "users": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M5 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" },
      { kind: "path", d: "M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" },
      { kind: "path", d: "M16 3.13a4 4 0 0 1 0 7.75" },
      { kind: "path", d: "M21 21v-2a4 4 0 0 0 -3 -3.85" },
    ],
  },
  // tabler: microphone
  "voice": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M9 5a3 3 0 0 1 3 -3a3 3 0 0 1 3 3v5a3 3 0 0 1 -3 3a3 3 0 0 1 -3 -3l0 -5" },
      { kind: "path", d: "M5 10a7 7 0 0 0 14 0" },
      { kind: "path", d: "M8 21l8 0" },
      { kind: "path", d: "M12 17l0 4" },
    ],
  },
  // tabler: hourglass
  "wait": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M6.5 7h11" },
      { kind: "path", d: "M6.5 17h11" },
      { kind: "path", d: "M6 20v-2a6 6 0 1 1 12 0v2a1 1 0 0 1 -1 1h-10a1 1 0 0 1 -1 -1" },
      { kind: "path", d: "M6 4v2a6 6 0 1 0 12 0v-2a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1" },
    ],
  },
  // tabler: webhook
  "webhook": {
    viewBoxSize: 24,
    elements: [
      { kind: "path", d: "M4.876 13.61a4 4 0 1 0 6.124 3.39h6" },
      { kind: "path", d: "M15.066 20.502a4 4 0 1 0 1.934 -7.502c-.706 0 -1.424 .179 -2 .5l-3 -5.5" },
      { kind: "path", d: "M16 8a4 4 0 1 0 -8 0c0 1.506 .77 2.818 2 3.5l-3 5.5" },
    ],
  },
};
