/**
 * Emits src/catalog/layout-editor/context/capabilities/
 * vocabulary.generated.ts
 * with the generated fragments used by the OBJECTS and CONNECTIONS sections
 * of the <capabilities> context block. The <vocabulary> body is rendered
 * from the object-preference registry
 * (packages/canvas/src/objects/registry/object-preferences.json — the single
 * roster shared by the picker, the tool surface, and the lints): one
 * <object> element per placeable name, in roster order (shapes first, then
 * glyphs), each carrying the preferred color, the meaning, and the use-when
 * bullets. The color roster (CANVAS_COLORS) and the connection enums still
 * come off the same schema tables the operation schemas declare.
 *
 * The exhaustive Records below require every connection-enum member to have
 * a roster entry. test/capabilities-generated.test.ts also keeps the
 * checked-in module byte-identical to this generator's output.
 *
 * Idempotent: bun scripts/generate-capabilities.ts
 */
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { CANVAS_COLORS } from "@codecaine-ai/canvas/schema";
import type {
  CanvasArrowDirection,
  CanvasConnectionStyle,
} from "@codecaine-ai/canvas/schema";
import type { Anchor } from "../../canvas/src/state/schema/connections";
import {
  OBJECT_PREFERENCES,
  type ObjectPreference,
} from "../../canvas/src/objects/registry";

// ---------------------------------------------------------------------------
// Connection enums — runtime lists checked against the schema types. Adding a
// member to any of these unions makes the corresponding Record incomplete,
// so the generator stops compiling until the roster is updated.
// ---------------------------------------------------------------------------

const ANCHOR_SIDES = ["top", "right", "bottom", "left"] as const satisfies readonly Anchor[];
const _anchorsExhaustive: Record<Anchor, true> = {
  top: true, right: true, bottom: true, left: true,
};
void _anchorsExhaustive;

const ARROW_KINDS = [
  "none", "forward", "back", "both",
] as const satisfies readonly CanvasArrowDirection[];
const _arrowsExhaustive: Record<CanvasArrowDirection, true> = {
  none: true, forward: true, back: true, both: true,
};
void _arrowsExhaustive;

const STYLE_KINDS = ["solid", "dashed"] as const satisfies readonly CanvasConnectionStyle[];
const _stylesExhaustive: Record<CanvasConnectionStyle, true> = { solid: true, dashed: true };
void _stylesExhaustive;

// ---------------------------------------------------------------------------
// The <vocabulary> body — the registry rendered as XML
// ---------------------------------------------------------------------------

/**
 * One sentence of color guidance, adjacent to the listing it governs
 * (docs/specs/operational-maps §Decisions, color guidance).
 */
const COLOR_GUIDANCE =
  "keep each object's preferred color; depart only when the object would sit "
  + "illegibly in its container";

/**
 * One registry entry as one visually distinct XML block: the name, the
 * preferred color, the meaning, and a dash bullet per use-when scenario.
 */
function objectElement(entry: ObjectPreference): string[] {
  return [
    `<object name="${entry.name}" preferred_color="${entry.color}">`,
    `    <meaning>${entry.meaning}</meaning>`,
    "    <use_when>",
    ...entry.scenarios.map((scenario) => `        - ${scenario}`),
    "    </use_when>",
    "</object>",
  ];
}

/** Flush-left <vocabulary> body; the assembly wraps and indents it. */
export function buildObjectsGenerated(): string {
  const lines: string[] = [];
  for (const entry of OBJECT_PREFERENCES) {
    lines.push(...objectElement(entry));
  }
  lines.push(COLOR_GUIDANCE);
  lines.push("colors (objects and connections), one per line:");
  for (const color of CANVAS_COLORS) {
    lines.push(`    ${color}`);
  }
  lines.push("these rosters are closed — draw every type and color from them");
  return lines.join("\n");
}

/** Flush-left <fields> body; the assembly wraps and indents it. */
export function buildConnectionFieldsGenerated(): string {
  return [
    `endpoint anchor: ${[...ANCHOR_SIDES, "center"].join(" | ")} — pins the side the wire uses; omit for automatic`,
    "endpoint position: [x,y] fractions 0..1 of the box, a finer pin than anchor",
    `arrow: ${ARROW_KINDS.join(" | ")} (default forward)`,
    `style: ${STYLE_KINDS.join(" | ")} (default solid)`,
    "waypoints: [x,y] world points the route must pass through",
  ].join("\n");
}

/** The full generated-module source, byte-stable across runs. */
export function renderVocabularyModule(): string {
  const objectLines = buildObjectsGenerated().split("\n");
  const connectionLines = buildConnectionFieldsGenerated().split("\n");
  return [
    "/**",
    " * GENERATED by scripts/generate-capabilities.ts — do not edit by hand.",
    " *",
    " * Generated fragments for the OBJECTS and CONNECTIONS sections of the",
    " * <capabilities> context block: the object-preference registry rendered",
    " * as the <vocabulary> XML — one <object> per placeable name, roster",
    " * order, with its preferred color, meaning, and use-when bullets (the",
    " * boot-time contact sheet carries the looks — geometry is the agent's to",
    " * choose) — plus the closed color roster and the connection field enums.",
    " * Regenerate: bun scripts/generate-capabilities.ts",
    " */",
    "",
    "export const CAPABILITIES_OBJECTS_GENERATED: string = [",
    ...objectLines.map((line) => `  ${JSON.stringify(line)},`),
    '].join("\\n");',
    "",
    "export const CAPABILITIES_CONNECTION_FIELDS_GENERATED: string = [",
    ...connectionLines.map((line) => `  ${JSON.stringify(line)},`),
    '].join("\\n");',
    "",
  ].join("\n");
}

const OUTPUT_FILE = join(
  resolve(import.meta.dir, ".."),
  "src", "catalog", "layout-editor", "context", "capabilities",
  "vocabulary.generated.ts",
);

if (import.meta.main) {
  writeFileSync(OUTPUT_FILE, renderVocabularyModule(), "utf8");
  console.log(`wrote ${OUTPUT_FILE}`);
}
