/**
 * Deterministic dev-icon codegen: Tabler outline glyphs + Simple Icons brand
 * logos for the canvas `icon` object's glyph registry.
 *
 * Reads tools/dev-icons/manifest.json and the byte-verbatim SVGs vendored under
 * tools/dev-icons/vendor/, and emits two serializable glyph-data modules beside
 * the icon object def (consumed whole by objects/shapes/icon/icon-glyphs.ts):
 *   1. icon-glyph-data-tabler.generated.ts — Tabler outline geometry for every
 *      generic glyph id (24-unit grid, stroke paint).
 *   2. icon-glyph-data-brands.generated.ts — Simple Icons logo geometry for
 *      every `brand-*` glyph id (24-unit grid, fill paint).
 *
 * Run:
 *   bun tools/dev-icons/generate.ts           offline: vendored SVGs → modules
 *   bun tools/dev-icons/generate.ts --vendor  network: re-vendor, then generate
 *
 * Pinning: manifest `packages` pins each upstream npm package to an exact
 * version AND its registry `dist.integrity`. `--vendor` downloads exactly that
 * tarball, refuses it unless its sha512 matches the pin, and checks each brand
 * entry's declared `license` against the per-logo license Simple Icons records
 * (absent = the package's CC0). Only when every package verifies does it copy
 * the SVGs the manifest names (plus each package's license file) into
 * vendor/<package>/, prune files no longer named, and rewrite
 * vendor/VERSIONS.md. To bump a package: set its new version + integrity (from
 * https://registry.npmjs.org/<npm>/<version> → dist.integrity), run with
 * --vendor, review the regenerated diff.
 *
 * The offline run never touches the network or the vendored files and is
 * idempotent: ids sorted, numbers fixed-precision, no timestamps, files only
 * rewritten when their bytes change. Tabler's invisible 24x24 bounding-box
 * path (`stroke="none" d="M0 0h24v24H0z"`) is stripped; rect / ellipse /
 * polyline / polygon convert to path data so every glyph stays inside the
 * registry's path | circle | line element model. All validation problems are
 * collected and reported together (the CLI then exits non-zero).
 *
 * No dependencies beyond node/bun builtins (plus the system `tar` for
 * --vendor). Both corpora are machine-generated and flat, so SVGs are parsed
 * with a small tokenizer, as in tools/nucleo-icons/generate.ts.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const TOOL_DIR = import.meta.dir;
const REPO_ROOT = resolve(TOOL_DIR, "..", "..");
const MANIFEST_PATH = resolve(TOOL_DIR, "manifest.json");
const VENDOR_DIR = resolve(TOOL_DIR, "vendor");
const VERSIONS_PATH = resolve(VENDOR_DIR, "VERSIONS.md");
/** Canvas-content output: glyph data co-locates with the icon object def. */
const GLYPH_OUT_DIR = resolve(REPO_ROOT, "packages", "canvas", "src", "objects", "shapes", "icon");
export const TABLER_OUT_PATH = resolve(GLYPH_OUT_DIR, "icon-glyph-data-tabler.generated.ts");
export const BRANDS_OUT_PATH = resolve(GLYPH_OUT_DIR, "icon-glyph-data-brands.generated.ts");

const GENERATED_HEADER =
  "// GENERATED by tools/dev-icons/generate.ts — do not edit; edit tools/dev-icons/manifest.json and re-run `bun tools/dev-icons/generate.ts`";

/** Tabler's invisible bounding-box path, stripped from every outline icon. */
const TABLER_BOUNDING_BOX_D = "M0 0h24v24H0z";

/**
 * The uniform outline paint every Tabler icon must declare on its root. The
 * registry strokes all generic glyphs with one renderer-chosen width, so an
 * icon that deviates (a filled dot, a custom width) is rejected, not drawn wrong.
 */
const TABLER_ROOT_PAINT: Record<string, string> = {
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  "stroke-width": "2",
  "stroke-linecap": "round",
  "stroke-linejoin": "round",
};

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

const PACKAGE_KEYS = ["tabler", "simple-icons"] as const;
type PackageKey = (typeof PACKAGE_KEYS)[number];

type PackagePin = {
  npm: string;
  version: string;
  integrity: string;
  license: string;
  /** License file at the package root, vendored beside the SVGs. */
  licenseFile: string;
  /** Directory (package-relative) holding `<source>.svg`. */
  iconDir: string;
};
type GlyphEntry = {
  id: string;
  source: string;
  /** Brands only: the SPDX id of a per-logo license Simple Icons records (absent = the package's CC0). */
  license?: string;
};
type Manifest = { packages: Record<PackageKey, PackagePin>; tabler: GlyphEntry[]; brands: GlyphEntry[] };

const BRAND_PREFIX = "brand-";

/** Simple Icons' icon metadata (package-relative) — read by --vendor to verify per-logo licenses, never vendored. */
const SIMPLE_ICONS_DATA = "data/simple-icons.json";

/** Load + validate the manifest; null (after recording problems) if unusable. */
function loadManifest(errors: string[]): Manifest | null {
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
  } catch (e) {
    errors.push(`manifest ${MANIFEST_PATH}: ${(e as Error).message}`);
    return null;
  }
  const manifest = raw as Manifest;
  for (const key of PACKAGE_KEYS) {
    const pin = manifest.packages?.[key];
    const fields = ["npm", "version", "integrity", "license", "licenseFile", "iconDir"] as const;
    if (!pin || fields.some((field) => typeof pin[field] !== "string" || pin[field].length === 0)) {
      errors.push(`manifest: packages.${key} must set ${fields.join(", ")}`);
    } else if (!pin.integrity.startsWith("sha512-")) {
      errors.push(`manifest: packages.${key}.integrity must be a sha512 dist.integrity`);
    }
  }
  const seen = new Set<string>();
  const checkList = (list: GlyphEntry[] | undefined, name: "tabler" | "brands") => {
    if (!Array.isArray(list)) {
      errors.push(`manifest: "${name}" must be an array of { id, source }`);
      return;
    }
    for (const entry of list) {
      if (typeof entry?.id !== "string" || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(entry.id)) {
        errors.push(`manifest ${name}: invalid id ${JSON.stringify(entry?.id)}`);
        continue;
      }
      if (seen.has(entry.id)) errors.push(`manifest: duplicate glyph id "${entry.id}"`);
      seen.add(entry.id);
      if ((name === "brands") !== entry.id.startsWith(BRAND_PREFIX)) {
        errors.push(`manifest ${name}: "${entry.id}" — brand ids (and only brand ids) start with "${BRAND_PREFIX}"`);
      }
      if (typeof entry.source !== "string" || !/^[a-z0-9_-]+$/.test(entry.source)) {
        errors.push(`manifest ${name}: "${entry.id}" has invalid source ${JSON.stringify(entry.source)}`);
      }
      if (entry.license !== undefined && (name !== "brands" || !/^[A-Za-z0-9.+-]+$/.test(entry.license))) {
        errors.push(`manifest ${name}: "${entry.id}" — "license" is an SPDX id, and only brand entries carry one`);
      }
    }
  };
  checkList(manifest.tabler, "tabler");
  checkList(manifest.brands, "brands");
  return errors.length === 0 ? manifest : null;
}

function entriesFor(manifest: Manifest, key: PackageKey): GlyphEntry[] {
  return key === "tabler" ? manifest.tabler : manifest.brands;
}

/** The distinct source names a package's entries draw from (two ids may share one SVG). */
function distinctSources(entries: GlyphEntry[]): string[] {
  return [...new Set(entries.map((entry) => entry.source))];
}

// ---------------------------------------------------------------------------
// SVG parsing (tokenizer — both corpora are flat and regular)
// ---------------------------------------------------------------------------

type SvgElement = { tag: string; attrs: Map<string, string> };
type ParsedSvg = {
  rootAttrs: Map<string, string>;
  viewBoxSize: number;
  title: string | null;
  elements: SvgElement[];
};

const SUPPORTED_CHILD_TAGS = new Set(["path", "rect", "line", "polyline", "polygon", "circle", "ellipse"]);
/** Pure geometry attributes — anything else on a child (paint, transform) is rejected. */
const GEOMETRY_ATTRS = new Set(["d", "x", "y", "width", "height", "rx", "ry", "cx", "cy", "r", "x1", "y1", "x2", "y2", "points"]);

function parseAttrs(raw: string): Map<string, string> {
  const attrs = new Map<string, string>();
  for (const m of raw.matchAll(/([\w:-]+)\s*=\s*"([^"]*)"/g)) attrs.set(m[1]!, m[2]!);
  return attrs;
}

function parseSvg(context: string, text: string, errors: string[]): ParsedSvg | null {
  const root = text.match(/<svg\b([^>]*)>/);
  if (!root) {
    errors.push(`${context}: no <svg> root element`);
    return null;
  }
  const rootAttrs = parseAttrs(root[1]!);
  const vb = (rootAttrs.get("viewBox") ?? "").trim().split(/[\s,]+/).map(Number);
  if (vb.length !== 4 || vb.some((n) => !Number.isFinite(n)) || vb[0] !== 0 || vb[1] !== 0 || vb[2] !== vb[3]) {
    errors.push(`${context}: viewBox must be a square "0 0 N N" (got "${rootAttrs.get("viewBox")}")`);
    return null;
  }
  const title = text.match(/<title>([^<]*)<\/title>/)?.[1] ?? null;
  const elements: SvgElement[] = [];
  let ok = true;
  for (const m of text.matchAll(/<([a-zA-Z][\w:-]*)\b([^>]*?)\/?>/g)) {
    const tag = m[1]!;
    if (tag === "svg" || tag === "title") continue;
    if (!SUPPORTED_CHILD_TAGS.has(tag)) {
      errors.push(`${context}: unsupported element <${tag}>`);
      ok = false;
      continue;
    }
    elements.push({ tag, attrs: parseAttrs(m[2]!) });
  }
  return ok ? { rootAttrs, viewBoxSize: vb[2]!, title, elements } : null;
}

// ---------------------------------------------------------------------------
// Geometry → glyph elements
// ---------------------------------------------------------------------------

type GlyphElementOut =
  | { kind: "path"; d: string }
  | { kind: "circle"; cx: number; cy: number; r: number }
  | { kind: "line"; x1: number; y1: number; x2: number; y2: number };

function fmtNum(n: number): string {
  const rounded = Math.round(n * 10000) / 10000;
  return String(Object.is(rounded, -0) ? 0 : rounded);
}

function convertElement(el: SvgElement, context: string, errors: string[]): GlyphElementOut | null {
  for (const name of el.attrs.keys()) {
    if (!GEOMETRY_ATTRS.has(name)) {
      errors.push(`${context}: <${el.tag}> carries non-geometry attribute "${name}" (glyphs take one renderer-chosen paint)`);
      return null;
    }
  }
  const num = (name: string, fallback?: number): number => {
    const raw = el.attrs.get(name);
    const value = raw === undefined ? fallback : Number(raw);
    if (value === undefined || !Number.isFinite(value)) {
      errors.push(`${context}: <${el.tag}> needs a numeric "${name}" (got ${JSON.stringify(raw)})`);
      return Number.NaN;
    }
    return value;
  };
  /** Fixed-precision number, as emitted (same rounding as path coordinates). */
  const fixed = (n: number) => Number(fmtNum(n));
  const p = (x: number, y: number) => `${fmtNum(x)} ${fmtNum(y)}`;
  const before = errors.length;
  let out: GlyphElementOut | null = null;

  switch (el.tag) {
    case "path": {
      const d = el.attrs.get("d");
      if (d) out = { kind: "path", d };
      else errors.push(`${context}: <path> missing "d"`);
      break;
    }
    case "circle":
      out = { kind: "circle", cx: fixed(num("cx", 0)), cy: fixed(num("cy", 0)), r: fixed(num("r")) };
      break;
    case "line":
      out = {
        kind: "line",
        x1: fixed(num("x1", 0)),
        y1: fixed(num("y1", 0)),
        x2: fixed(num("x2", 0)),
        y2: fixed(num("y2", 0)),
      };
      break;
    case "rect": {
      const [x, y, w, h] = [num("x", 0), num("y", 0), num("width"), num("height")];
      const rxRaw = el.attrs.has("rx") ? num("rx") : undefined;
      const ryRaw = el.attrs.has("ry") ? num("ry") : undefined;
      const rx = Math.min(rxRaw ?? ryRaw ?? 0, w / 2);
      const ry = Math.min(ryRaw ?? rxRaw ?? 0, h / 2);
      if (rx === 0 || ry === 0) {
        out = { kind: "path", d: `M ${p(x, y)} L ${p(x + w, y)} L ${p(x + w, y + h)} L ${p(x, y + h)} Z` };
      } else {
        const arc = (tx: number, ty: number) => `A ${fmtNum(rx)} ${fmtNum(ry)} 0 0 1 ${p(tx, ty)}`;
        out = {
          kind: "path",
          d: [
            `M ${p(x + rx, y)}`, `L ${p(x + w - rx, y)}`, arc(x + w, y + ry),
            `L ${p(x + w, y + h - ry)}`, arc(x + w - rx, y + h),
            `L ${p(x + rx, y + h)}`, arc(x, y + h - ry),
            `L ${p(x, y + ry)}`, arc(x + rx, y), "Z",
          ].join(" "),
        };
      }
      break;
    }
    case "ellipse": {
      const [cx, cy, rx, ry] = [num("cx", 0), num("cy", 0), num("rx"), num("ry")];
      const r = `${fmtNum(rx)} ${fmtNum(ry)}`;
      out = { kind: "path", d: `M ${p(cx - rx, cy)} A ${r} 0 1 0 ${p(cx + rx, cy)} A ${r} 0 1 0 ${p(cx - rx, cy)} Z` };
      break;
    }
    case "polyline":
    case "polygon": {
      const nums = (el.attrs.get("points") ?? "").trim().split(/[\s,]+/).filter(Boolean).map(Number);
      if (nums.length < 4 || nums.length % 2 !== 0 || nums.some((n) => !Number.isFinite(n))) {
        errors.push(`${context}: <${el.tag}> has unparseable points`);
        break;
      }
      const pts: string[] = [];
      for (let i = 0; i < nums.length; i += 2) pts.push(p(nums[i]!, nums[i + 1]!));
      out = { kind: "path", d: `M ${pts.join(" L ")}${el.tag === "polygon" ? " Z" : ""}` };
      break;
    }
  }
  return errors.length === before ? out : null;
}

type GlyphBlock = { id: string; comment: string; viewBoxSize: number; elements: GlyphElementOut[] };

/** One Tabler outline icon → glyph block (root paint checked, bounding box stripped). */
function tablerGlyph(entry: GlyphEntry, text: string, errors: string[]): GlyphBlock | null {
  const context = `tabler/${entry.source}.svg (glyph "${entry.id}")`;
  const svg = parseSvg(context, text, errors);
  if (!svg) return null;
  let ok = true;
  for (const [name, value] of Object.entries(TABLER_ROOT_PAINT)) {
    if (svg.rootAttrs.get(name) !== value) {
      errors.push(`${context}: root ${name}="${svg.rootAttrs.get(name)}" (outline glyphs need ${name}="${value}")`);
      ok = false;
    }
  }
  const elements: GlyphElementOut[] = [];
  for (const el of svg.elements) {
    if (el.attrs.get("stroke") === "none") {
      // The only unpainted child Tabler ships is the 24x24 bounding box.
      if (el.tag !== "path" || el.attrs.get("d") !== TABLER_BOUNDING_BOX_D) {
        errors.push(`${context}: unexpected unstroked <${el.tag}> (only the bounding-box path is stripped)`);
        ok = false;
      }
      continue;
    }
    const out = convertElement(el, context, errors);
    if (out) elements.push(out);
    else ok = false;
  }
  if (ok && elements.length === 0) {
    errors.push(`${context}: no drawable elements`);
    ok = false;
  }
  return ok ? { id: entry.id, comment: `tabler: ${entry.source}`, viewBoxSize: svg.viewBoxSize, elements } : null;
}

/** One Simple Icons logo → glyph block (exactly one filled path). */
function brandGlyph(entry: GlyphEntry, text: string, errors: string[]): GlyphBlock | null {
  const context = `simple-icons/${entry.source}.svg (glyph "${entry.id}")`;
  const svg = parseSvg(context, text, errors);
  if (!svg) return null;
  if (svg.viewBoxSize !== 24 || svg.elements.length !== 1 || svg.elements[0]!.tag !== "path" || !svg.title) {
    errors.push(`${context}: expected a titled 24x24 logo with exactly one <path>`);
    return null;
  }
  const out = convertElement(svg.elements[0]!, context, errors);
  const license = entry.license ? ` — logo license ${entry.license}` : "";
  return out
    ? { id: entry.id, comment: `simple-icons: ${entry.source} (${svg.title})${license}`, viewBoxSize: 24, elements: [out] }
    : null;
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

function emitElement(el: GlyphElementOut): string {
  switch (el.kind) {
    case "path":
      return `{ kind: "path", d: ${JSON.stringify(el.d)} }`;
    case "circle":
      return `{ kind: "circle", cx: ${el.cx}, cy: ${el.cy}, r: ${el.r} }`;
    case "line":
      return `{ kind: "line", x1: ${el.x1}, y1: ${el.y1}, x2: ${el.x2}, y2: ${el.y2} }`;
  }
}

function emitModule(exportName: string, provenance: string[], doc: string, blocks: GlyphBlock[]): string {
  const sorted = [...blocks].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return [
    GENERATED_HEADER,
    ...provenance.map((line) => `// ${line}`),
    "",
    "// Structural twin of IconGlyphElement in ./icon-glyphs.ts (kept local to",
    "// avoid an import cycle — the shapes must stay assignment-compatible).",
    "type IconGlyphElement =",
    '  | { kind: "path"; d: string }',
    '  | { kind: "circle"; cx: number; cy: number; r: number }',
    '  | { kind: "line"; x1: number; y1: number; x2: number; y2: number };',
    "",
    `/** ${doc} */`,
    `export const ${exportName}: Record<`,
    "  string,",
    "  { viewBoxSize: number; elements: readonly IconGlyphElement[] }",
    "> = {",
    ...sorted.map((block) =>
      [
        `  // ${block.comment}`,
        `  ${JSON.stringify(block.id)}: {`,
        `    viewBoxSize: ${block.viewBoxSize},`,
        "    elements: [",
        ...block.elements.map((el) => `      ${emitElement(el)},`),
        "    ],",
        "  },",
      ].join("\n"),
    ),
    "};",
    "",
  ].join("\n");
}

export type DevIconModules = { tabler: string; brands: string };

/**
 * Render both generated modules from the manifest + vendored SVGs. Pure apart
 * from reading files: throws one Error listing every validation problem.
 */
export function renderDevIconModules(): DevIconModules {
  const errors: string[] = [];
  const manifest = loadManifest(errors);
  if (!manifest) throw new Error(`dev icons: ${errors.length} error(s):\n  - ${errors.join("\n  - ")}`);

  const build = (key: PackageKey, toBlock: typeof tablerGlyph): GlyphBlock[] => {
    const blocks: GlyphBlock[] = [];
    for (const entry of entriesFor(manifest, key)) {
      const path = resolve(VENDOR_DIR, key, `${entry.source}.svg`);
      if (!existsSync(path)) {
        errors.push(`${key}/${entry.source}.svg (glyph "${entry.id}") is not vendored — run \`bun tools/dev-icons/generate.ts --vendor\``);
        continue;
      }
      const block = toBlock(entry, readFileSync(path, "utf8"), errors);
      if (block) blocks.push(block);
    }
    return blocks;
  };
  const tablerBlocks = build("tabler", tablerGlyph);
  const brandBlocks = build("simple-icons", brandGlyph);
  if (errors.length > 0) throw new Error(`dev icons: ${errors.length} error(s):\n  - ${errors.join("\n  - ")}`);

  const tabler = manifest.packages.tabler;
  const brands = manifest.packages["simple-icons"];
  return {
    tabler: emitModule(
      "TABLER_ICON_GLYPH_ELEMENTS",
      [
        `Source: ${tabler.npm}@${tabler.version} ${tabler.iconDir} (${tabler.license}) — vendored in tools/dev-icons/vendor/tabler/;`,
        "attribution in tools/dev-icons/THIRD-PARTY-NOTICES.md.",
      ],
      "Tabler outline geometry per glyph id — 24-unit grid, stroke paint, bounding-box path stripped.",
      tablerBlocks,
    ),
    brands: emitModule(
      "BRAND_ICON_GLYPH_ELEMENTS",
      [
        `Source: ${brands.npm}@${brands.version} ${brands.iconDir} (${brands.license}, except entries that name their own logo license) —`,
        "vendored in tools/dev-icons/vendor/simple-icons/. Logos are trademarks of their respective owners; see",
        "tools/dev-icons/THIRD-PARTY-NOTICES.md.",
      ],
      "Simple Icons logo geometry per `brand-*` glyph id — 24-unit grid, fill paint.",
      brandBlocks,
    ),
  };
}

// ---------------------------------------------------------------------------
// --vendor: fetch the pinned tarballs and copy the named files
// ---------------------------------------------------------------------------

/** Write `bytes` to `path` only when they differ (no mtime churn). */
function writeIfChanged(path: string, bytes: string | Buffer): boolean {
  const next = typeof bytes === "string" ? Buffer.from(bytes, "utf8") : bytes;
  if (existsSync(path) && readFileSync(path).equals(next)) return false;
  writeFileSync(path, next);
  return true;
}

function tarballUrl(pin: PackagePin): string {
  return `https://registry.npmjs.org/${pin.npm}/-/${pin.npm.split("/").pop()}-${pin.version}.tgz`;
}

/** One verified package's vendored files, held in memory until every package verifies. */
type StagedPackage = { key: PackageKey; files: Map<string, Buffer> };

/**
 * Download one pinned tarball, verify its sha512, and extract the license
 * file plus every SVG the manifest names. Records problems and returns null
 * on any failure — nothing is written to vendor/ here.
 */
async function stagePackage(manifest: Manifest, key: PackageKey, errors: string[]): Promise<StagedPackage | null> {
  const pin = manifest.packages[key];
  const url = tarballUrl(pin);
  let tgz: Buffer;
  try {
    const response = await fetch(url);
    if (!response.ok) {
      errors.push(`${key}: GET ${url} → HTTP ${response.status}`);
      return null;
    }
    tgz = Buffer.from(await response.arrayBuffer());
  } catch (e) {
    errors.push(`${key}: GET ${url} failed: ${(e as Error).message}`);
    return null;
  }
  const integrity = `sha512-${createHash("sha512").update(tgz).digest("base64")}`;
  if (integrity !== pin.integrity) {
    errors.push(`${key}: ${pin.npm}@${pin.version} tarball integrity ${integrity} does not match the pinned ${pin.integrity}`);
    return null;
  }
  const work = mkdtempSync(join(tmpdir(), "dev-icons-"));
  try {
    const tgzPath = join(work, "package.tgz");
    writeFileSync(tgzPath, tgz);
    // Distinct members only: GNU tar rejects a member named twice.
    const vendored = [pin.licenseFile, ...distinctSources(entriesFor(manifest, key)).map((source) => `${pin.iconDir}/${source}.svg`)];
    const members = key === "simple-icons" ? [...vendored, SIMPLE_ICONS_DATA] : vendored;
    const tar = Bun.spawnSync(["tar", "-xzf", tgzPath, "-C", work, ...members.map((member) => `package/${member}`)]);
    if (tar.exitCode !== 0) {
      errors.push(`${key}: extracting from ${pin.npm}@${pin.version} failed (a source name may not exist in this version):\n${tar.stderr.toString().trim()}`);
      return null;
    }
    if (key === "simple-icons") {
      checkBrandLicenses(manifest, JSON.parse(readFileSync(join(work, "package", SIMPLE_ICONS_DATA), "utf8")), errors);
    }
    const files = new Map<string, Buffer>();
    for (const member of vendored) {
      files.set(member.split("/").pop()!, readFileSync(join(work, "package", member)));
    }
    return { key, files };
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

/**
 * Each brand entry's `license` must match the per-logo license Simple Icons
 * records for its slug (none = the package's CC0), so a version bump cannot
 * silently change what THIRD-PARTY-NOTICES.md has to say.
 */
function checkBrandLicenses(manifest: Manifest, data: unknown, errors: string[]): void {
  if (!Array.isArray(data)) {
    errors.push(`simple-icons: ${SIMPLE_ICONS_DATA} is not an icon list`);
    return;
  }
  const bySlug = new Map((data as { slug?: string; license?: { type?: string } }[]).map((icon) => [icon.slug, icon]));
  for (const entry of manifest.brands) {
    const icon = bySlug.get(entry.source);
    if (!icon) {
      errors.push(`simple-icons: "${entry.id}" — slug "${entry.source}" is missing from ${SIMPLE_ICONS_DATA}`);
    } else if (icon.license?.type !== entry.license) {
      errors.push(
        `simple-icons: "${entry.id}" — Simple Icons records logo license ${icon.license?.type ?? "none (CC0)"} but manifest.json says ${entry.license ?? "none"}; update manifest.json and THIRD-PARTY-NOTICES.md`,
      );
    }
  }
}

/** Write a staged package into vendor/<package>/ (which --vendor owns), pruning files it no longer names. */
function commitPackage(staged: StagedPackage): void {
  const outDir = resolve(VENDOR_DIR, staged.key);
  mkdirSync(outDir, { recursive: true });
  for (const [name, bytes] of staged.files) writeIfChanged(resolve(outDir, name), bytes);
  for (const name of readdirSync(outDir)) {
    if (!staged.files.has(name)) rmSync(resolve(outDir, name));
  }
}

function versionsNote(manifest: Manifest): string {
  const rows = PACKAGE_KEYS.map((key) => {
    const pin = manifest.packages[key];
    const entries = entriesFor(manifest, key);
    return `| \`${key}/\` | \`${pin.npm}\` | ${pin.version} | ${pin.license} (\`${key}/${pin.licenseFile}\`) | ${distinctSources(entries).length} SVGs for ${entries.length} glyph ids, from \`${pin.iconDir}/\` |`;
  });
  return [
    "# Vendored icon sources",
    "",
    "Written by `bun tools/dev-icons/generate.ts --vendor` from `../manifest.json` — do not edit by hand.",
    "Each file is a byte-verbatim copy out of the pinned npm tarball below; only the SVGs the manifest",
    "names are vendored, plus each package's license file.",
    "",
    "| dir | npm package | version | license | vendored |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    "Per-logo licenses that Simple Icons records are declared on the brand entries in `../manifest.json`",
    "and verified against the package's `data/simple-icons.json` on every `--vendor` run.",
    "",
    "Pinned tarballs (sha512 `dist.integrity`, verified on every `--vendor` run):",
    "",
    ...PACKAGE_KEYS.map((key) => `- ${tarballUrl(manifest.packages[key])}\n  \`${manifest.packages[key].integrity}\``),
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const errors: string[] = [];
  if (process.argv.includes("--vendor")) {
    const manifest = loadManifest(errors);
    if (manifest) {
      const staged: StagedPackage[] = [];
      for (const key of PACKAGE_KEYS) {
        const pkg = await stagePackage(manifest, key, errors);
        if (pkg) staged.push(pkg);
      }
      // All or nothing: vendor/ only changes once every package verified.
      if (errors.length === 0) {
        for (const pkg of staged) commitPackage(pkg);
        writeIfChanged(VERSIONS_PATH, versionsNote(manifest));
      }
    }
    if (errors.length > 0) {
      console.error(`dev icons: ${errors.length} error(s):\n  - ${errors.join("\n  - ")}`);
      process.exit(1);
    }
    console.log(`dev icons: vendored pinned sources → ${VENDOR_DIR}`);
  }

  let modules: DevIconModules;
  try {
    modules = renderDevIconModules();
  } catch (e) {
    console.error((e as Error).message);
    process.exit(1);
  }
  for (const [path, text] of [[TABLER_OUT_PATH, modules.tabler], [BRANDS_OUT_PATH, modules.brands]] as const) {
    const changed = writeIfChanged(path, text);
    console.log(`dev icons: ${changed ? "wrote" : "unchanged"} ${path}`);
  }
}

if (import.meta.main) await main();
