import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { CANVAS_ICON_GLYPHS } from "../../../../state/schema/object-types";
import { BRAND_ICON_GLYPH_ELEMENTS } from "../icon-glyph-data-brands.generated";
import { TABLER_ICON_GLYPH_ELEMENTS } from "../icon-glyph-data-tabler.generated";
import { GENERATED_ICON_GLYPH_ELEMENTS } from "../icon-glyph-data.generated";
import { ICON_GLYPHS, ICON_GLYPH_CATEGORIES, ICON_PACK_IDS, resolveIconGlyph } from "../icon-glyphs";
import {
  BRANDS_OUT_PATH,
  TABLER_OUT_PATH,
  renderDevIconModules,
} from "../../../../../../../tools/dev-icons/generate";

/**
 * The theme-aware glyph registry: the schema roster (CANVAS_ICON_GLYPHS) is
 * the one id list; every id resolves in both icon packs — `nucleo` keeps the
 * Nucleo glyph wherever one exists (today's drawing, pixel-identical) and
 * falls back to Tabler, `tabler` draws Tabler outlines — while `brand-*` ids
 * always draw their filled Simple Icons logo. The Tabler and Simple Icons
 * geometry is generated by tools/dev-icons/generate.ts from vendored SVGs.
 */

const BRAND_IDS = CANVAS_ICON_GLYPHS.filter((id) => id.startsWith("brand-"));
const GENERIC_IDS = CANVAS_ICON_GLYPHS.filter((id) => !id.startsWith("brand-"));

describe("generated glyph corpora", () => {
  it("cover exactly the schema roster: Tabler for every generic id, Simple Icons for every brand, Nucleo for generic ids only", () => {
    expect(Object.keys(TABLER_ICON_GLYPH_ELEMENTS).sort()).toEqual([...GENERIC_IDS].sort());
    expect(Object.keys(BRAND_ICON_GLYPH_ELEMENTS).sort()).toEqual([...BRAND_IDS].sort());
    for (const id of Object.keys(GENERATED_ICON_GLYPH_ELEMENTS)) {
      expect(GENERIC_IDS as readonly string[], id).toContain(id);
    }
  });

  it("are fresh and deterministic: re-running the generator on the vendored SVGs reproduces the checked-in modules byte for byte", () => {
    const regenerated = renderDevIconModules();
    expect(readFileSync(TABLER_OUT_PATH, "utf8")).toBe(regenerated.tabler);
    expect(readFileSync(BRANDS_OUT_PATH, "utf8")).toBe(regenerated.brands);
  });
});

describe("resolveIconGlyph", () => {
  it("resolves every roster id in both packs to drawable geometry with a label and a known, non-empty category", () => {
    const categoryIds: string[] = ICON_GLYPH_CATEGORIES.map((category) => category.id);
    for (const pack of ICON_PACK_IDS) {
      const labels = new Set<string>();
      const usedCategories = new Set<string>();
      for (const id of CANVAS_ICON_GLYPHS) {
        const glyph = resolveIconGlyph(id, pack);
        expect(glyph.id, `${pack}/${id}`).toBe(id);
        expect(glyph.elements.length, `${pack}/${id}`).toBeGreaterThan(0);
        expect(glyph.viewBoxSize, `${pack}/${id}`).toBeGreaterThan(0);
        expect(glyph.label.length, `${pack}/${id}`).toBeGreaterThan(0);
        expect(categoryIds, `${pack}/${id}`).toContain(glyph.category);
        labels.add(glyph.label);
        usedCategories.add(glyph.category);
      }
      expect(labels.size, `${pack} labels are unique`).toBe(CANVAS_ICON_GLYPHS.length);
      expect([...usedCategories].sort(), `${pack} leaves no category empty`).toEqual([...categoryIds].sort());
    }
  });

  it("draws brand ids as the filled Simple Icons logo in both packs, and only brand ids group under brands", () => {
    for (const id of CANVAS_ICON_GLYPHS) {
      const isBrand = id.startsWith("brand-");
      for (const pack of ICON_PACK_IDS) {
        const glyph = resolveIconGlyph(id, pack);
        expect(glyph.category === "brands", `${pack}/${id}`).toBe(isBrand);
        if (isBrand) {
          expect(glyph.source, `${pack}/${id}`).toBe("simple-icons");
          expect(glyph.paint, `${pack}/${id}`).toBe("fill");
          expect(glyph.elements, `${pack}/${id}`).toBe(BRAND_ICON_GLYPH_ELEMENTS[id]!.elements);
        }
      }
    }
  });

  it("draws every generic id as a stroked Tabler outline in the tabler pack, with Tabler's bounding-box path stripped", () => {
    for (const id of GENERIC_IDS) {
      const glyph = resolveIconGlyph(id, "tabler");
      expect(glyph.source, id).toBe("tabler");
      expect(glyph.paint, id).toBe("stroke");
      expect(glyph.viewBoxSize, id).toBe(24);
      for (const element of glyph.elements) {
        if (element.kind === "path") {
          expect(element.d.replace(/\s+/g, ""), id).not.toStartWith("M00h24v24H0");
        }
      }
    }
  });

  it("keeps the Nucleo glyph in the nucleo pack wherever one exists and falls back to the Tabler glyph otherwise", () => {
    for (const id of GENERIC_IDS) {
      const glyph = resolveIconGlyph(id, "nucleo");
      const nucleo = GENERATED_ICON_GLYPH_ELEMENTS[id];
      if (nucleo) {
        expect(glyph.source, id).toBe("nucleo");
        expect(glyph.paint, id).toBe("stroke");
        expect(glyph.viewBoxSize, id).toBe(nucleo.viewBoxSize);
        expect(glyph.elements, id).toBe(nucleo.elements);
      } else {
        expect(glyph, id).toBe(resolveIconGlyph(id, "tabler"));
      }
      // ICON_GLYPHS — what today's renderers draw — is the nucleo pack.
      expect(ICON_GLYPHS[id], id).toBe(glyph);
    }
  });

  it("returns undefined for a missing id or a string outside the roster, including prototype keys", () => {
    for (const pack of ICON_PACK_IDS) {
      expect(resolveIconGlyph(undefined, pack)).toBeUndefined();
      expect(resolveIconGlyph("unicorn", pack)).toBeUndefined();
      expect(resolveIconGlyph("constructor", pack)).toBeUndefined();
    }
  });
});
