/**
 * Deterministic Nucleo icon codegen.
 *
 * Reads packages/canvas/src/ui/icons/manifest.json and emits:
 *   1. packages/canvas/src/ui/icons/nucleo/<kebab>-icon.tsx — one React chrome
 *      component per icon, plus a nucleo/index.ts barrel re-exporting them all.
 *   2. packages/canvas/src/objects/shapes/icon/icon-glyph-data.generated.ts —
 *      a single serializable glyph-data registry (consumed whole). Canvas
 *      CONTENT, so it co-locates with the icon object def, not with the
 *      interface icons (co-location alignment).
 *
 * Run: bun tools/nucleo-icons/generate.ts
 *
 * Source SVGs are resolved against the canonical Nucleo library, discovered in
 * this order:
 *   (a) --library <dir> CLI flag
 *   (b) NUCLEO_LIBRARY_DIR env var
 *   (c) the default Dropbox library path
 *   (d) the vendored copy under nucleo/svg/ (self-sufficient on CI / other
 *       machines where the library is absent)
 * Every SVG resolved from the library is vendored byte-verbatim into
 * nucleo/svg/ (source path "/" → "--") so the vendored copy alone can
 * regenerate identical output. The generator owns the nucleo/ directory: it
 * rewrites every .tsx/.ts it emits and prunes vendored SVGs no longer
 * referenced by the manifest.
 *
 * No dependencies beyond node/bun builtins. The Nucleo corpus is
 * machine-generated and regular, so SVGs are parsed with a small tokenizer
 * rather than a full XML parser. All validation problems are collected and
 * reported together before exiting non-zero.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { resolve } from "node:path";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const REPO_ROOT = resolve(import.meta.dir, "..", "..");
const ICONS_DIR = resolve(REPO_ROOT, "packages", "canvas", "src", "ui", "icons");
const NUCLEO_DIR = resolve(ICONS_DIR, "nucleo");
const VENDOR_DIR = resolve(NUCLEO_DIR, "svg");
const MANIFEST_PATH = resolve(ICONS_DIR, "manifest.json");
/** Canvas-content output: the glyph registry co-locates with the icon object def. */
const GLYPH_OUT_PATH = resolve(
  REPO_ROOT,
  "packages",
  "canvas",
  "src",
  "objects",
  "shapes",
  "icon",
  "icon-glyph-data.generated.ts",
);

const DEFAULT_LIBRARY_DIR = "/Users/Ford/Dropbox/UI Components/Icons/nucleo";

const GENERATED_HEADER =
  "// GENERATED by tools/nucleo-icons/generate.ts — do not edit; edit manifest.json and re-run `bun tools/nucleo-icons/generate.ts`";

// ---------------------------------------------------------------------------
// Library resolution
// ---------------------------------------------------------------------------

/** Resolve the --library <dir> CLI flag, if present. */
function libraryFromArgv(): string | null {
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--library") return argv[i + 1] ?? null;
    if (a.startsWith("--library=")) return a.slice("--library=".length);
  }
  return null;
}

/**
 * The ordered list of candidate library roots. The first that both exists and
 * contains the requested source is used. The vendored copy is always the last
 * resort so CI / library-less machines still regenerate.
 */
function libraryRoots(): string[] {
  const roots: string[] = [];
  const fromArgv = libraryFromArgv();
  if (fromArgv) roots.push(resolve(fromArgv));
  const fromEnv = process.env.NUCLEO_LIBRARY_DIR;
  if (fromEnv) roots.push(resolve(fromEnv));
  roots.push(DEFAULT_LIBRARY_DIR);
  return roots;
}

const LIBRARY_ROOTS = libraryRoots();

/** source path (nucleo_ui/outline/.../18px_check.svg) → vendored basename. */
function vendorName(source: string): string {
  return source.split("/").join("--");
}

// ---------------------------------------------------------------------------
// Manifest types
// ---------------------------------------------------------------------------

type ChromeEntry = { export: string; source?: string; custom?: boolean };
type GlyphEntry = { id: string; source: string };
type Manifest = { chrome?: ChromeEntry[]; glyphs?: GlyphEntry[] };

// ---------------------------------------------------------------------------
// Error collection
// ---------------------------------------------------------------------------

const errors: string[] = [];

function fail(message: string): void {
  errors.push(message);
}

// ---------------------------------------------------------------------------
// SVG parsing (tokenizer — corpus SVGs are flat and regular)
// ---------------------------------------------------------------------------

type SvgElement = {
  tag: string;
  /** Attribute name → value, in source order. */
  attrs: Map<string, string>;
};

type ParsedSvg = {
  viewBox: string;
  /** Square viewBox side length (validation guarantees width === height). */
  viewBoxSize: number;
  elements: SvgElement[];
};

const SUPPORTED_CHILD_TAGS = new Set([
  "path",
  "rect",
  "line",
  "polyline",
  "polygon",
  "circle",
  "ellipse",
]);

function parseAttrs(raw: string): Map<string, string> {
  const attrs = new Map<string, string>();
  const re = /([\w:-]+)\s*=\s*"([^"]*)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    attrs.set(m[1]!, m[2]!);
  }
  return attrs;
}

/** Parse one SVG's text. Returns null (after recording errors) if unusable. */
function parseSvg(source: string, text: string): ParsedSvg | null {
  const rootMatch = text.match(/<svg\b([^>]*)>/);
  if (!rootMatch) {
    fail(`${source}: no <svg> root element found`);
    return null;
  }
  const rootAttrs = parseAttrs(rootMatch[1]!);
  const viewBox = rootAttrs.get("viewBox");
  if (!viewBox) {
    fail(`${source}: root <svg> has no viewBox`);
    return null;
  }
  const vb = viewBox.trim().split(/[\s,]+/).map(Number);
  if (vb.length !== 4 || vb.some((n) => !Number.isFinite(n))) {
    fail(`${source}: unparseable viewBox "${viewBox}"`);
    return null;
  }
  const [minX, minY, width, height] = vb as [number, number, number, number];
  let ok = true;
  if (minX !== 0 || minY !== 0) {
    fail(`${source}: viewBox origin must be 0 0 (got "${viewBox}")`);
    ok = false;
  }
  if (width !== height) {
    fail(`${source}: non-square viewBox "${viewBox}" (${width}x${height})`);
    ok = false;
  }

  // Every open tag other than the root. Corpus elements are flat (no <g>,
  // no nesting inside shape elements), written as `<path ...></path>`.
  const elements: SvgElement[] = [];
  const tagRe = /<([a-zA-Z][\w:-]*)\b([^>]*?)\/?>/g;
  let m: RegExpExecArray | null;
  while ((m = tagRe.exec(text)) !== null) {
    const tag = m[1]!;
    if (tag === "svg") continue;
    if (!SUPPORTED_CHILD_TAGS.has(tag)) {
      fail(`${source}: unsupported element <${tag}>`);
      ok = false;
      continue;
    }
    elements.push({ tag, attrs: parseAttrs(m[2]!) });
  }
  if (elements.length === 0 && ok) {
    fail(`${source}: no drawable elements found`);
    ok = false;
  }
  return ok ? { viewBox, viewBoxSize: width, elements } : null;
}

// ---------------------------------------------------------------------------
// Number formatting (deterministic, compact)
// ---------------------------------------------------------------------------

function fmtNum(n: number): string {
  const rounded = Math.round(n * 10000) / 10000;
  const clean = Object.is(rounded, -0) ? 0 : rounded;
  return String(clean);
}

// ---------------------------------------------------------------------------
// Transform parsing (translate/rotate only — rigid transforms)
// ---------------------------------------------------------------------------

/** 2x3 affine matrix [a, b, c, d, e, f]: (x,y) → (ax + cy + e, bx + dy + f). */
type Matrix = [number, number, number, number, number, number];

const IDENTITY: Matrix = [1, 0, 0, 1, 0, 0];

function multiply(m1: Matrix, m2: Matrix): Matrix {
  return [
    m1[0] * m2[0] + m1[2] * m2[1],
    m1[1] * m2[0] + m1[3] * m2[1],
    m1[0] * m2[2] + m1[2] * m2[3],
    m1[1] * m2[2] + m1[3] * m2[3],
    m1[0] * m2[4] + m1[2] * m2[5] + m1[4],
    m1[1] * m2[4] + m1[3] * m2[5] + m1[5],
  ];
}

function apply(m: Matrix, x: number, y: number): [number, number] {
  return [m[0] * x + m[2] * y + m[4], m[1] * x + m[3] * y + m[5]];
}

/** Net rotation of a rigid matrix, in degrees (for arc x-axis-rotation). */
function rotationDeg(m: Matrix): number {
  return (Math.atan2(m[1], m[0]) * 180) / Math.PI;
}

/**
 * Parse a transform list into a matrix. Only translate()/rotate() are
 * supported (all the corpus uses); anything else records an error.
 */
function parseTransform(value: string, context: string): Matrix | null {
  let matrix: Matrix = IDENTITY;
  const re = /([a-zA-Z]+)\s*\(([^)]*)\)/g;
  let m: RegExpExecArray | null;
  let matched = false;
  while ((m = re.exec(value)) !== null) {
    matched = true;
    const fn = m[1]!;
    const args = m[2]!.trim().split(/[\s,]+/).filter(Boolean).map(Number);
    if (args.some((n) => !Number.isFinite(n))) {
      fail(`${context}: unparseable transform arguments in "${value}"`);
      return null;
    }
    if (fn === "translate" && (args.length === 1 || args.length === 2)) {
      matrix = multiply(matrix, [1, 0, 0, 1, args[0]!, args[1] ?? 0]);
    } else if (fn === "rotate" && (args.length === 1 || args.length === 3)) {
      const rad = (args[0]! * Math.PI) / 180;
      const rot: Matrix = [Math.cos(rad), Math.sin(rad), -Math.sin(rad), Math.cos(rad), 0, 0];
      if (args.length === 3) {
        const [, cx, cy] = args as [number, number, number];
        matrix = multiply(matrix, [1, 0, 0, 1, cx, cy]);
        matrix = multiply(matrix, rot);
        matrix = multiply(matrix, [1, 0, 0, 1, -cx, -cy]);
      } else {
        matrix = multiply(matrix, rot);
      }
    } else {
      fail(`${context}: unsupported transform function "${fn}(${m[2]})" (only translate/rotate)`);
      return null;
    }
  }
  if (!matched) {
    fail(`${context}: unparseable transform "${value}"`);
    return null;
  }
  return matrix;
}

// ---------------------------------------------------------------------------
// Attribute handling shared by both outputs
// ---------------------------------------------------------------------------

const DROPPED_ATTRS = new Set(["id", "class"]);

/** data-color / data-name / data-stroke etc — Nucleo metadata, never rendered. */
function isDroppedAttr(name: string): boolean {
  return DROPPED_ATTRS.has(name) || name.startsWith("data-");
}

/** kebab-case SVG presentation attributes → JSX camelCase. */
const JSX_ATTR_NAMES: Record<string, string> = {
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-miterlimit": "strokeMiterlimit",
  "stroke-dasharray": "strokeDasharray",
  "stroke-dashoffset": "strokeDashoffset",
  "stroke-opacity": "strokeOpacity",
  "fill-rule": "fillRule",
  "fill-opacity": "fillOpacity",
  "clip-rule": "clipRule",
};

/** Attributes passed through unchanged (already valid JSX names). */
const PASSTHROUGH_ATTRS = new Set([
  "d",
  "points",
  "x",
  "y",
  "width",
  "height",
  "rx",
  "ry",
  "cx",
  "cy",
  "r",
  "x1",
  "y1",
  "x2",
  "y2",
  "fill",
  "stroke",
  "opacity",
  "transform",
]);

function isPaintReference(value: string): boolean {
  return value.startsWith("url(");
}

// ---------------------------------------------------------------------------
// Output 1: chrome icon components (nucleo/<kebab>.tsx)
// ---------------------------------------------------------------------------

/** AlertTriangleIcon → alert-triangle-icon */
function kebabCase(exportName: string): string {
  return exportName
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function emitTsxElement(el: SvgElement, source: string): string | null {
  const parts: string[] = [];
  let ok = true;
  for (const [name, value] of el.attrs) {
    if (isDroppedAttr(name)) continue;
    let outName: string;
    if (PASSTHROUGH_ATTRS.has(name)) {
      outName = JSX_ATTR_NAMES[name] ?? name;
    } else if (name in JSX_ATTR_NAMES) {
      outName = JSX_ATTR_NAMES[name]!;
    } else {
      fail(`${source}: unsupported attribute "${name}" on <${el.tag}>`);
      ok = false;
      continue;
    }
    let outValue = value;
    if ((name === "stroke" || name === "fill") && isPaintReference(value)) {
      fail(`${source}: unsupported paint reference ${name}="${value}" on <${el.tag}>`);
      ok = false;
      continue;
    }
    if (name === "stroke" && value !== "none") outValue = "currentColor";
    if (name === "fill" && value !== "none") outValue = "currentColor";
    parts.push(`${outName}="${outValue}"`);
  }
  if (!ok) return null;
  return `<${el.tag} ${parts.join(" ")} />`;
}

/** Full per-icon .tsx module source for one component. */
function emitTsxModule(exportName: string, svg: ParsedSvg, source: string): string | null {
  const children: string[] = [];
  let ok = true;
  for (const el of svg.elements) {
    const line = emitTsxElement(el, source);
    if (line === null) ok = false;
    else children.push(`      ${line}`);
  }
  if (!ok) return null;
  return [
    GENERATED_HEADER,
    '"use client";',
    "",
    'import type { IconProps } from "../icon-props";',
    "",
    `/** ${source} */`,
    `export function ${exportName}({ className, style }: IconProps) {`,
    "  return (",
    `    <svg viewBox="${svg.viewBox}" className={className} style={style} fill="none" aria-hidden="true">`,
    ...children,
    "    </svg>",
    "  );",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Output 2: glyph data (icon-glyph-data.generated.ts)
// ---------------------------------------------------------------------------

type GlyphElementOut =
  | { kind: "path"; d: string }
  | { kind: "circle"; cx: number; cy: number; r: number }
  | { kind: "line"; x1: number; y1: number; x2: number; y2: number };

function num(el: SvgElement, name: string, context: string, fallback?: number): number | null {
  const raw = el.attrs.get(name);
  if (raw === undefined) {
    if (fallback !== undefined) return fallback;
    fail(`${context}: <${el.tag}> missing required attribute "${name}"`);
    return null;
  }
  const n = Number(raw);
  if (!Number.isFinite(n)) {
    fail(`${context}: <${el.tag}> has non-numeric ${name}="${raw}"`);
    return null;
  }
  return n;
}

function elementMatrix(el: SvgElement, context: string): Matrix | null {
  const t = el.attrs.get("transform");
  if (t === undefined) return IDENTITY;
  return parseTransform(t, context);
}

function parsePoints(raw: string, context: string): [number, number][] | null {
  const nums = raw.trim().split(/[\s,]+/).filter(Boolean).map(Number);
  if (nums.length < 4 || nums.length % 2 !== 0 || nums.some((n) => !Number.isFinite(n))) {
    fail(`${context}: unparseable points="${raw}"`);
    return null;
  }
  const pts: [number, number][] = [];
  for (let i = 0; i < nums.length; i += 2) pts.push([nums[i]!, nums[i + 1]!]);
  return pts;
}

/** Rounded (or plain) rect → path d, with the rigid transform baked in. */
function rectToPathD(el: SvgElement, m: Matrix, context: string): string | null {
  const x = num(el, "x", context, 0);
  const y = num(el, "y", context, 0);
  const w = num(el, "width", context);
  const h = num(el, "height", context);
  if (x === null || y === null || w === null || h === null) return null;
  let rx = el.attrs.has("rx") ? num(el, "rx", context) : null;
  let ry = el.attrs.has("ry") ? num(el, "ry", context) : null;
  if (rx === null && ry !== null) rx = ry;
  if (ry === null && rx !== null) ry = rx;
  rx = Math.min(rx ?? 0, w / 2);
  ry = Math.min(ry ?? 0, h / 2);

  const p = (px: number, py: number) => apply(m, px, py).map(fmtNum).join(" ");
  if (rx === 0 || ry === 0) {
    return `M ${p(x, y)} L ${p(x + w, y)} L ${p(x + w, y + h)} L ${p(x, y + h)} Z`;
  }
  const rot = fmtNum(rotationDeg(m));
  const arc = (tx: number, ty: number) => `A ${fmtNum(rx!)} ${fmtNum(ry!)} ${rot} 0 1 ${p(tx, ty)}`;
  return [
    `M ${p(x + rx, y)}`,
    `L ${p(x + w - rx, y)}`,
    arc(x + w, y + ry),
    `L ${p(x + w, y + h - ry)}`,
    arc(x + w - rx, y + h),
    `L ${p(x + rx, y + h)}`,
    arc(x, y + h - ry),
    `L ${p(x, y + ry)}`,
    arc(x + rx, y),
    "Z",
  ].join(" ");
}

/** Ellipse → path d (two arcs), with the rigid transform baked in. */
function ellipseToPathD(el: SvgElement, m: Matrix, context: string): string | null {
  const cx = num(el, "cx", context, 0);
  const cy = num(el, "cy", context, 0);
  const rx = num(el, "rx", context);
  const ry = num(el, "ry", context);
  if (cx === null || cy === null || rx === null || ry === null) return null;
  const rot = fmtNum(rotationDeg(m));
  const p = (px: number, py: number) => apply(m, px, py).map(fmtNum).join(" ");
  const west = p(cx - rx, cy);
  const east = p(cx + rx, cy);
  const r = `${fmtNum(rx)} ${fmtNum(ry)}`;
  return `M ${west} A ${r} ${rot} 1 0 ${east} A ${r} ${rot} 1 0 ${west} Z`;
}

function convertGlyphElement(el: SvgElement, context: string): GlyphElementOut | null {
  for (const [name, value] of el.attrs) {
    if ((name === "stroke" || name === "fill") && isPaintReference(value)) {
      fail(`${context}: unsupported paint reference ${name}="${value}" on <${el.tag}>`);
      return null;
    }
  }
  const m = elementMatrix(el, context);
  if (m === null) return null;
  const hasTransform = el.attrs.has("transform");

  switch (el.tag) {
    case "path": {
      if (hasTransform) {
        fail(
          `${context}: <path> with transform is not supported in glyph data (path data cannot be rewritten)`,
        );
        return null;
      }
      const d = el.attrs.get("d");
      if (!d) {
        fail(`${context}: <path> missing "d"`);
        return null;
      }
      return { kind: "path", d };
    }
    case "circle": {
      const cx = num(el, "cx", context, 0);
      const cy = num(el, "cy", context, 0);
      const r = num(el, "r", context);
      if (cx === null || cy === null || r === null) return null;
      const [tx, ty] = apply(m, cx, cy);
      return {
        kind: "circle",
        cx: Number(fmtNum(tx)),
        cy: Number(fmtNum(ty)),
        r: Number(fmtNum(r)),
      };
    }
    case "line": {
      const x1 = num(el, "x1", context, 0);
      const y1 = num(el, "y1", context, 0);
      const x2 = num(el, "x2", context, 0);
      const y2 = num(el, "y2", context, 0);
      if (x1 === null || y1 === null || x2 === null || y2 === null) return null;
      const [tx1, ty1] = apply(m, x1, y1);
      const [tx2, ty2] = apply(m, x2, y2);
      return {
        kind: "line",
        x1: Number(fmtNum(tx1)),
        y1: Number(fmtNum(ty1)),
        x2: Number(fmtNum(tx2)),
        y2: Number(fmtNum(ty2)),
      };
    }
    case "rect": {
      const d = rectToPathD(el, m, context);
      return d === null ? null : { kind: "path", d };
    }
    case "ellipse": {
      const d = ellipseToPathD(el, m, context);
      return d === null ? null : { kind: "path", d };
    }
    case "polyline":
    case "polygon": {
      const raw = el.attrs.get("points");
      if (!raw) {
        fail(`${context}: <${el.tag}> missing "points"`);
        return null;
      }
      const pts = parsePoints(raw, context);
      if (pts === null) return null;
      const mapped = pts.map(([px, py]) => apply(m, px, py).map(fmtNum).join(" "));
      const d =
        `M ${mapped[0]} ` +
        mapped
          .slice(1)
          .map((pt) => `L ${pt}`)
          .join(" ") +
        (el.tag === "polygon" ? " Z" : "");
      return { kind: "path", d };
    }
    default:
      fail(`${context}: unsupported element <${el.tag}> in glyph data`);
      return null;
  }
}

function emitGlyphElement(el: GlyphElementOut): string {
  switch (el.kind) {
    case "path":
      return `{ kind: "path", d: ${JSON.stringify(el.d)} }`;
    case "circle":
      return `{ kind: "circle", cx: ${el.cx}, cy: ${el.cy}, r: ${el.r} }`;
    case "line":
      return `{ kind: "line", x1: ${el.x1}, y1: ${el.y1}, x2: ${el.x2}, y2: ${el.y2} }`;
  }
}

// ---------------------------------------------------------------------------
// Source loading + vendoring
// ---------------------------------------------------------------------------

/** Source paths that were successfully vendored this run (for pruning). */
const vendoredThisRun = new Set<string>();

/**
 * Return the raw SVG text for a manifest source, resolving it against the
 * library roots (copying byte-verbatim into the vendored dir) and falling back
 * to the vendored copy. Records an error and returns null if unresolvable.
 */
function loadSourceText(source: string): string | null {
  const vendorPath = resolve(VENDOR_DIR, vendorName(source));

  for (const root of LIBRARY_ROOTS) {
    const abs = resolve(root, source);
    if (existsSync(abs)) {
      const bytes = readFileSync(abs);
      // Only rewrite the vendored file if its bytes differ, keeping output
      // deterministic and avoiding needless churn.
      if (!existsSync(vendorPath) || !readFileSync(vendorPath).equals(bytes)) {
        writeFileSync(vendorPath, bytes);
      }
      vendoredThisRun.add(source);
      return bytes.toString("utf8");
    }
  }

  if (existsSync(vendorPath)) {
    vendoredThisRun.add(source);
    return readFileSync(vendorPath, "utf8");
  }

  fail(
    `${source}: source not found in the Nucleo library (checked ${LIBRARY_ROOTS.join(
      ", ",
    )}) nor in the vendored copy at ${vendorPath}`,
  );
  return null;
}

function loadSource(source: string): ParsedSvg | null {
  const text = loadSourceText(source);
  if (text === null) return null;
  return parseSvg(source, text);
}

// ---------------------------------------------------------------------------
// Directory ownership (deterministic state of nucleo/)
// ---------------------------------------------------------------------------

/** Ensure nucleo/ and nucleo/svg/ exist. */
function ensureDirs(): void {
  mkdirSync(VENDOR_DIR, { recursive: true });
}

/** Delete every .tsx/.ts directly under nucleo/ (the generator owns them). */
function clearGeneratedModules(): void {
  if (!existsSync(NUCLEO_DIR)) return;
  for (const name of readdirSync(NUCLEO_DIR)) {
    if (name.endsWith(".tsx") || name.endsWith(".ts")) {
      rmSync(resolve(NUCLEO_DIR, name));
    }
  }
}

/** Prune vendored SVGs no longer referenced by the manifest. */
function pruneVendored(): void {
  if (!existsSync(VENDOR_DIR)) return;
  const keep = new Set([...vendoredThisRun].map(vendorName));
  for (const name of readdirSync(VENDOR_DIR)) {
    if (name.endsWith(".svg") && !keep.has(name)) {
      rmSync(resolve(VENDOR_DIR, name));
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function loadManifest(): Manifest | null {
  if (!existsSync(MANIFEST_PATH)) {
    fail(`manifest not found at ${MANIFEST_PATH}`);
    return null;
  }
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as Manifest;
  } catch (e) {
    fail(`manifest is not valid JSON: ${(e as Error).message}`);
    return null;
  }
}

function main(): void {
  const manifest = loadManifest();
  if (manifest === null) {
    report(0, 0, 0);
    return;
  }
  const chrome = manifest.chrome ?? [];
  const glyphs = manifest.glyphs ?? [];

  ensureDirs();

  // --- Validate manifest shape / duplicates -------------------------------
  const seenExports = new Set<string>();
  for (const entry of chrome) {
    if (typeof entry.export !== "string" || !/^[A-Za-z_$][\w$]*$/.test(entry.export)) {
      fail(`chrome entry has invalid export name: ${JSON.stringify(entry.export)}`);
      continue;
    }
    if (seenExports.has(entry.export)) fail(`duplicate chrome export name "${entry.export}"`);
    seenExports.add(entry.export);
    if (!entry.custom && typeof entry.source !== "string") {
      fail(`chrome entry "${entry.export}" is not custom but has no source`);
    }
  }
  const seenIds = new Set<string>();
  for (const entry of glyphs) {
    if (typeof entry.id !== "string" || entry.id.length === 0) {
      fail(`glyph entry has invalid id: ${JSON.stringify(entry.id)}`);
      continue;
    }
    if (seenIds.has(entry.id)) fail(`duplicate glyph id "${entry.id}"`);
    seenIds.add(entry.id);
    if (typeof entry.source !== "string") {
      fail(`glyph entry "${entry.id}" has no source`);
    }
  }

  // --- Chrome components (one module per icon) -----------------------------
  const chromeSorted = [...chrome]
    .filter((e) => !e.custom && typeof e.source === "string")
    .sort((a, b) => (a.export < b.export ? -1 : a.export > b.export ? 1 : 0));

  // { exportName, fileBase } for the barrel, in export order.
  const modules: { exportName: string; fileBase: string; text: string }[] = [];
  for (const entry of chromeSorted) {
    const svg = loadSource(entry.source!);
    if (svg === null) continue;
    const text = emitTsxModule(entry.export, svg, entry.source!);
    if (text !== null) {
      modules.push({ exportName: entry.export, fileBase: kebabCase(entry.export), text });
    }
  }

  // --- Glyph data -----------------------------------------------------------
  const glyphBlocks: string[] = [];
  const glyphsSorted = [...glyphs]
    .filter((e) => typeof e.source === "string")
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  for (const entry of glyphsSorted) {
    const svg = loadSource(entry.source);
    if (svg === null) continue;
    const context = `${entry.source} (glyph "${entry.id}")`;
    const converted: GlyphElementOut[] = [];
    let ok = true;
    for (const el of svg.elements) {
      const out = convertGlyphElement(el, context);
      if (out === null) ok = false;
      else converted.push(out);
    }
    if (!ok) continue;
    glyphBlocks.push(
      [
        `  // ${entry.source}`,
        `  ${JSON.stringify(entry.id)}: {`,
        `    viewBoxSize: ${svg.viewBoxSize},`,
        "    elements: [",
        ...converted.map((el) => `      ${emitGlyphElement(el)},`),
        "    ],",
        "  },",
      ].join("\n"),
    );
  }

  if (errors.length > 0) {
    report(0, 0, 0);
    return;
  }

  // --- Write outputs --------------------------------------------------------
  clearGeneratedModules();

  for (const mod of modules) {
    writeFileSync(resolve(NUCLEO_DIR, `${mod.fileBase}.tsx`), mod.text, "utf8");
  }

  const barrel = [
    GENERATED_HEADER,
    "",
    'export type { IconProps } from "../icon-props";',
    "",
    ...modules.map((mod) => `export { ${mod.exportName} } from "./${mod.fileBase}";`),
    "",
  ].join("\n");
  writeFileSync(resolve(NUCLEO_DIR, "index.ts"), barrel, "utf8");

  const glyphOut = [
    GENERATED_HEADER,
    "",
    "// Structural twin of IconGlyphElement in ./icon-glyphs.ts (kept local to",
    "// avoid an import cycle — the shapes must stay assignment-compatible).",
    "type IconGlyphElement =",
    '  | { kind: "path"; d: string }',
    '  | { kind: "circle"; cx: number; cy: number; r: number }',
    '  | { kind: "line"; x1: number; y1: number; x2: number; y2: number };',
    "",
    "export const GENERATED_ICON_GLYPH_ELEMENTS: Record<",
    "  string,",
    "  { viewBoxSize: number; elements: readonly IconGlyphElement[] }",
    "> = {",
    glyphBlocks.join("\n"),
    "};",
    "",
  ].join("\n");
  writeFileSync(GLYPH_OUT_PATH, glyphOut, "utf8");

  pruneVendored();

  report(modules.length, glyphBlocks.length, vendoredThisRun.size);
}

function report(componentCount: number, glyphCount: number, vendoredCount: number): void {
  if (errors.length > 0) {
    console.error(`nucleo icons: ${errors.length} error(s):`);
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }
  console.log(`nucleo icons: wrote ${componentCount} chrome component module(s) → ${NUCLEO_DIR}`);
  console.log(`nucleo icons: wrote ${glyphCount} glyph entr(ies) → ${GLYPH_OUT_PATH}`);
  console.log(`nucleo icons: vendored ${vendoredCount} distinct source SVG(s) → ${VENDOR_DIR}`);
}

main();
