// GENERATED by tools/nucleo-icons/generate.ts — do not edit; edit manifest.json and re-run `bun tools/nucleo-icons/generate.ts`
"use client";

import type { IconProps } from "../icon-props";

/** nucleo_ui/outline/editing/18px_text-bold.svg */
export function BoldIcon({ className, style }: IconProps) {
  return (
    <svg viewBox="0 0 18 18" className={className} style={style} fill="none" aria-hidden="true">
      <path d="M6.75 2.25H10C11.795 2.25 13.25 3.71 13.25 5.5C13.25 7.29 11.795 8.75 10 8.75H6.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
      <path d="M6.75 8.75H10.75C12.683 8.75 14.25 10.3199 14.25 12.25C14.25 14.1801 12.683 15.75 10.75 15.75H6.75" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
      <path d="M6.75 15.75H4.75C4.198 15.75 3.75 15.3 3.75 14.75V3.25C3.75 2.7 4.198 2.25 4.75 2.25H6.75V15.75Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
    </svg>
  );
}
