// GENERATED by tools/nucleo-icons/generate.ts — do not edit; edit manifest.json and re-run `bun tools/nucleo-icons/generate.ts`
"use client";

import type { IconProps } from "../icon-props";

/** nucleo_ui/outline/ui-layout/18px_check.svg */
export function CheckIcon({ className, style }: IconProps) {
  return (
    <svg viewBox="0 0 18 18" className={className} style={style} fill="none" aria-hidden="true">
      <polyline points="2.75 9.25 6.75 14.25 15.25 3.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" />
    </svg>
  );
}
