// GENERATED by tools/nucleo-icons/generate.ts — do not edit; edit manifest.json and re-run `bun tools/nucleo-icons/generate.ts`
"use client";

import type { IconProps } from "../icon-props";

/** nucleo_ui/outline/arrows/18px_chevron-down.svg */
export function ChevronDownIcon({ className, style }: IconProps) {
  return (
    <svg viewBox="0 0 18 18" className={className} style={style} fill="none" aria-hidden="true">
      <polyline points="15.25 6.5 9 12.75 2.75 6.5" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.25" />
    </svg>
  );
}
