// GENERATED by tools/nucleo-icons/generate.ts — do not edit; edit manifest.json and re-run `bun tools/nucleo-icons/generate.ts`
"use client";

import type { IconProps } from "../icon-props";

/** nucleo_ui/outline/files/18px_note-3.svg */
export function StickyIcon({ className, style }: IconProps) {
  return (
    <svg viewBox="0 0 18 18" className={className} style={style} fill="none" aria-hidden="true">
      <line x1="7.25" y1="11.75" x2="5.75" y2="11.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.25" />
      <line x1="8" y1="9" x2="5.75" y2="9" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.25" />
      <line x1="12.25" y1="6.25" x2="5.75" y2="6.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.25" />
      <path d="m4.75,2.75h8.5c1.1046,0,2,.8954,2,2v5.1716c0,.5304-.2107,1.0391-.5858,1.4142l-3.3284,3.3284c-.3751.3751-.8838.5858-1.4142.5858h-5.1716c-1.1046,0-2-.8954-2-2V4.75c0-1.1046.8954-2,2-2Z" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.25" />
      <path d="m10.25,15.148v-3.898c0-.552.448-1,1-1h3.91" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.25" />
    </svg>
  );
}
